FROM hirurglybitel/gdmn-firebird-pm2:latest as builder
WORKDIR /usr/app

ARG NX_BRANCH
ARG NX_HOST_IP
ARG NX_SERVER_PORT

ENV NX_BRANCH=${NX_BRANCH:-no-branch}
ENV NX_HOST_IP=$NX_HOST_IP
ENV NX_SERVER_PORT=$NX_SERVER_PORT

COPY . .

RUN yarn install --network-timeout 1000000 --immutable --immutable-cache --check-cache --parallel && \
    yarn cache clean && \
    yarn nx clear-cache && \
    yarn build

FROM hirurglybitel/gdmn-firebird-pm2:latest as server
WORKDIR /usr/app
COPY --from=builder /usr/app/dist/apps/api-1 /usr/app/dist/apps/api-1
COPY --from=builder /usr/app/node_modules /usr/app/node_modules
COPY pm2.config.js .

ENV PM2_PUBLIC_KEY 2g0zthb6mp3oq16
ENV PM2_SECRET_KEY 4ml4ivoyodxnapp

ENTRYPOINT ["pm2-runtime", "start", "pm2.config.js"]

FROM nginx:stable-alpine3.17-slim as client
COPY --from=builder /usr/app/dist/apps/app-1  /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]
