version: '3'

services:
  back:
    image: server:v4
    build:
      context: .
      dockerfile: DockerFile
      target: server
      # args:
      #   - NX_SERVER_PORT=${NX_SERVER_PORT}
      #   - NX_HOST_IP=${NX_HOST_IP}
    container_name: server
    ports:
      - "${NX_SERVER_PORT}:${NX_SERVER_PORT}"
    env_file:
      - .env
  app:
    image: react:v4
    build:
      context: .
      dockerfile: DockerFile
      target: react
      args:
        - NX_HOST_IP=${NX_HOST_IP}
        - NX_SERVER_PORT=${NX_SERVER_PORT}
    container_name: react
    ports:
      - ${NX_APP_PORT}:80
      - 5200:80
    env_file:
      - .env
